spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: CLIENTID
            client-secret: CLIENTSECRET
            scope:
              - user:email
              - read:user
              - 
        provider:
          github:
            authorizationUri: https://github.com/login/oauth/authorize
            tokenUri: https://github.com/login/oauth/access_token
            userInfoUri: https://api.github.com/user
            userNameAttribute: login